apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aks-demo-app
  template:
    metadata:
      labels:
        app: aks-demo-app
    spec:
      containers:
      - name: aks-demo-app
        image: kiranacrdevops.azurecr.io/aks-demo-app:20e7679ec80d0d415a09b2e52fa0fc45f9045736
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: staging
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
