name: AKS Deployment Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'

permissions:
  id-token: write    # Required for OIDC authentication
  contents: read     # Allows reading repository contents

env:
  ACR_NAME: kiranacrdevops
  AKS_CLUSTER_NAME: dev-aks-cluster
  RESOURCE_GROUP: spoke1-rg
  APP_NAME: aks-demo-app

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}

  deploy-to-aks:
    runs-on: ubuntu-latest
    needs: [build-test-push]
    env:
      IMAGE_TAG: ${{ github.sha }}
      DEPLOY_ENV: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'staging' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS Credentials
        uses: azure/aks-set-context@v3
        with:
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}
          resource-group: ${{ env.RESOURCE_GROUP }}

      - name: Replace placeholders in deployment.yaml
        run: |
          # Replace placeholders in deployment.yaml with actual values
          sed -i "s,{{APP_NAME}},${{ env.APP_NAME }}," ./k8s/deployment.yaml
          sed -i "s,{{DEPLOY_ENV}},${{ env.DEPLOY_ENV }}," ./k8s/deployment.yaml
          sed -i "s,TEST_IMAGE_NAME,${{ env.ACR_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}," ./k8s/deployment.yaml

      - name: Replace placeholders in service.yaml
        run: |
          # Replace placeholders in service.yaml
          sed -i "s,{{APP_NAME}},${{ env.APP_NAME }}," ./k8s/service.yaml
          sed -i "s,{{DEPLOY_ENV}},${{ env.DEPLOY_ENV }}," ./k8s/service.yaml

      - name: Apply Kubernetes Manifests
        run: |
          # Apply the final YAML files after the image name is replaced
          kubectl apply -f ./k8s/
        
      - name: Get Application URL
        run: |
          APP_URL=$(kubectl get service ${{ env.APP_NAME }}-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "Application URL: $APP_URL"
